$(function(){
	if($.cookie('user')!='admin'){
		location.href="admin.php";
	}
	$(".exit").hover(function(){
		$(this).css('color','red');
	},function(){
		$(this).css('color','blue');
	}).click(function(){
		$.removeCookie('user');
		location.href="admin_c.php";
	});
});